### ISSUE TITLE
A rob command 

### ISSUE THREAD

**Issue by DreadVoice** [aoi-bot/Aoi#22]
A rob command which allows you to rob others wallet with an equal chance of getting away with some money and being caught. It would be a fun addition

**Comment by Naia-love** [comment]
ughhh. i hate this command on dank memer, you just have to be in a server you dont check often who have the bot to loose alllllll your money in a few hours.

**Comment by crazygmr101** [comment]
That is true, but there are some additional options

- The permissions module already allows server owners to turn it off
- It could possibly be adjusted by server owners
- I *could* implement a wallet/bank system, and commands like rob would only take from the wallet. But if I do that, what happens to other money earned? Does that go in wallet? Bank?

**Comment by DreadVoice** [comment]
> That is true, but there are some additional options
> 
> * The permissions module already allows server owners to turn it off
> * It could possibly be adjusted by server owners
> * I _could_ implement a wallet/bank system, and commands like rob would only take from the wallet. But if I do that, what happens to other money earned? Does that go in wallet? Bank?

It by default goes to the wallet and you can send it in the bank. You can also have a setting that makes the money go to the bank directly. Also there will be a limit on how much money can enter the bank. And also passive mode can be a thing.

**Comment by crazygmr101** [comment]
Passive mode? O.o
