### ISSUE TITLE
Have an UNO command so we can play UNO

### ISSUE THREAD

**Issue by DreadVoice** [aoi-bot/Aoi#26]

**Comment by AlaRubra123** [comment]
That seems like hell to implement, especially since uno relies on hidden information, so the bot would have to DM you your hand. Would be not great UX to play, and I don't see a good way around that.

**Comment by crazygmr101** [comment]
It's not a super terrible idea. I just don't think I know enough about asyncio yet to manage that, cuz I can imagine a couple race conditions that I can't think of a Way around off the top of my head.
