### ISSUE TITLE
MAKE A SIMP COMMAND

### ISSUE THREAD

**Issue by CataDev0** [aoi-bot/Aoi#33]
**Is your feature request related to a problem? Please describe.**
### _NO._ 

**- [ No ]** 

**Describe the solution you'd like**
_**MAKE A SIMP COMMAND THAT ALLOWS YOU TO EMBARASS YOUR SIMP FRIEND.**_

- [ yes ] 

**Describe alternatives you've considered**
_USING MY OWN BOT._

- [ yes! ] 

**...OR ALA'S**

- [ yes! ] 

- [ yes? ] 

**Additional context**

> USE THE SIMP BUTTON MEME OR ANY OTHER IDC. I JUST WANT AOI TO BE ABLE TO EMBARASS MY SIMP FRIENDS
EXAMPLE: 

> ,SIMP CRAZYGMR101

- [ ] 

- [ ] 

- [ Ahh yes. ]

**Comment by CataDev0** [comment]
Pls giv me simp cmd

**Comment by AlaRubra123** [comment]
Yes

**Comment by AlaRubra123** [comment]
Flan isn't public, but he could cherrypick the commit for Naoto

**Comment by crazygmr101** [comment]
Smh. I'll do it for aoi. Just. Other things first

**Comment by StrangeEcho** [comment]
yes I agree
