### ISSUE TITLE
salad :)

### ISSUE THREAD

**Issue by salad-byte** [aoi-bot/Aoi#39]
**Is your feature request related to a problem? Please describe.**
Yes. The problem is that I want salad :(

**Describe the solution you'd like**
A salad command

**Describe alternatives you've considered**
Actually making the salad, but thats a shit idea :(

**Additional context**
![image](https://user-images.githubusercontent.com/78463713/106702249-a3653a80-65ad-11eb-8d11-8597aef608e3.png)

**Comment by crazygmr101** [comment]
Closing because what the fuck

**Comment by person4848** [comment]
Well Aoi does need a salad command... so you should probably implement it

**Comment by AlaRubra123** [comment]
Yeah. S A L A D

**Comment by crazygmr101** [comment]
![image](https://user-images.githubusercontent.com/22755628/106705994-90099d80-65b4-11eb-8936-e8c95c0ec272.png)

**Comment by StrangeEcho** [comment]
i lik sala to

**Comment by AlaRubra123** [comment]
> i lik sala to

Wow, 4 words in the comment and the only one spelled correctly is a single letter.

**Comment by crazygmr101** [comment]
Implemented in 949406bff753decba108911d49cf1c273f825621
