### ISSUE TITLE
,moverole borks hierarchy sumthin fierce

### ISSUE THREAD

**Issue by AlaRubra123** [aoi-bot/Aoi#47]
Like, totally borked.
![](https://cdn.discordapp.com/attachments/788661880881152026/843070950878871552/Screenshot_20210515-052233_Discord.jpg)

**Comment by crazygmr101** [comment]
I didn't see an issue in Aoi's code for this and couldn't repro, but did update https://github.com/aoi-bot/Aoi/discord.py/ to 2.0, so if a bug was present upstream it should have been fixed. 

Feel free to reopen if it happens again.

**Comment by AlaRubra123** [comment]
I can't seem to re-open, but it's different broken after updating.

**Comment by crazygmr101** [comment]
Gonna submit an issue on the d.py repo, cuz this seems like a not aoi thing

**Comment by crazygmr101** [comment]
Closing in 07c989ee4e06c39a554d746503fdcd1ef3da7da4 by removing the command, because it is clear that d.py can not be trusted when it comes to role ordering.
