### ISSUE TITLE
Fix windows when?

### ISSUE THREAD

**Issue by StrangeEcho** [aoi-bot/Aoi#51]
Self hosting aoi on windows still doesn't work.

**Comment by crazygmr101** [comment]
I removed the one dependency that was causing the trouble. Running on the develop branch should fix it, otherwise, wait for this issue to be auto-closed when the changes get merged.

**Comment by crazygmr101** [comment]
Reopening cuz I'm an idiot and closed it myself right after saying it'll be autoclosed. :dumb:
